import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a "Next" and "Previous" navigation
 - create a generated index page for docs in the same category
 */
const sidebars: SidebarsConfig = {
  // Auto-generate sidebar from docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;